#:schema="node_modules/wrangler/config-schema.json"
name = "workers-prometheus-example"
main = "src/index.ts"
compatibility_date = "2024-08-06"

[[durable_objects.bindings]]
name = "PROMETHEUS"
class_name = "PROMETHEUS"

[[migrations]]
new_classes=["PROMETHEUS"]
tag = "v1"
