packages:
  - package
  - example
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
minimumReleaseAgeExclude:
  - micromatch@4.0.8
  - undici@5.28.5 || 5.29.0 || 6.23.0 || 6.24.0 || 6.27.0
  - path-to-regexp@6.3.0
  - esbuild@0.24.3
  - cookie@0.7.0
  - '@babel/helpers@7.26.10'
  - nanoid@3.3.8
  - node-forge@1.3.2 || 1.3.4 || 1.4.0
  - wrangler@3.114.17
  - picomatch@2.3.2
  - defu@6.1.5
  - ws@8.20.1 || 8.21.0
  - '@babel/core@7.29.1'
